// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.zanox.connect


trait ConnectServicePortType {
  def getSession(authToken: String, publicKey: String, signature: String, nonce: String, timestamp: String): Either[scalaxb.Soap11Fault[org.zanox.connect.SoapException], org.zanox.connect.GetSessionResponse]
  def createConnect(applicationId: String, connectId: String, publicKey: String, timestamp: String, nonce: String, signature: String): Either[scalaxb.Soap11Fault[org.zanox.connect.SoapException], String]
  def getUiUrl(connectId: String, sessionKey: String, timestamp: String, nonce: String, signature: String): Either[scalaxb.Soap11Fault[org.zanox.connect.SoapException], String]
  def closeSession(connectId: String, publicKey: String, timestamp: String, nonce: String, signature: String): Either[scalaxb.Soap11Fault[org.zanox.connect.SoapException], org.zanox.connect.CloseSessionResponse]
  def promoteSession(connectId: String, promoteType: org.zanox.connect.PromoteTypeEnum, publicKey: String, timestamp: String, nonce: String, signature: String): Either[scalaxb.Soap11Fault[org.zanox.connect.SoapException], org.zanox.connect.PromoteSessionResponse]
}




