// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.zanox.connect


case class GetSession(authToken: String,
  publicKey: String,
  signature: String,
  nonce: String,
  timestamp: String)


case class GetSessionResponse(session: Option[org.zanox.connect.SessionType] = None)


case class SessionType(connectId: String,
  sessionKey: Option[String] = None,
  secretKey: Option[String] = None,
  sessionExpires: Int,
  permanent: Boolean)


case class CreateConnectRequest(applicationId: String,
  connectId: String,
  publicKey: String,
  timestamp: String,
  nonce: String,
  signature: String)


case class CreateConnectResponse(connectId: String)


case class ConnectType(connectId: String,
  applicationId: String,
  loginId: Int,
  accessTime: javax.xml.datatype.XMLGregorianCalendar,
  createTime: javax.xml.datatype.XMLGregorianCalendar,
  status: Int)


case class GetUiUrl(connectId: String,
  sessionKey: String,
  timestamp: String,
  nonce: String,
  signature: String)


case class GetUiUrlResponse(url: String)


case class SoapException(message: String,
  code: Int)


case class CloseSession(connectId: String,
  publicKey: String,
  timestamp: String,
  nonce: String,
  signature: String)


case class CloseSessionResponse()


case class PromoteSessionRequest(connectId: String,
  promoteType: org.zanox.connect.PromoteTypeEnum,
  publicKey: String,
  timestamp: String,
  nonce: String,
  signature: String)


case class PromoteSessionResponse(wsSessionExpires: Int,
  uiSessionExpires: Int)

trait PromoteTypeEnum

object PromoteTypeEnum {
  def fromString(value: String): PromoteTypeEnum = value match {
    case "UISESSION" => UISESSION
    case "WSSESSION" => WSSESSION
    case "BOTH" => BOTH

  }
}

case object UISESSION extends PromoteTypeEnum { override def toString = "UISESSION" }
case object WSSESSION extends PromoteTypeEnum { override def toString = "WSSESSION" }
case object BOTH extends PromoteTypeEnum { override def toString = "BOTH" }

